# workflow to build and deploy slides to github pages

name: BuildPages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for "main-real" branch
  pull_request:
    branches: [ "main-real" ]
  push:
    branches: [ "main-real" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Workflow run - one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build" that builds pages site and slides
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      
      - name: Render Quarto Project
        run: |
          cd slides
          quarto render git_for_science.qmd
          cd ../

      - name: Test pages build
        if: github.ref != 'refs/heads/main-real'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: pages-test # The branch the action should deploy to.
          folder: slides      # The folder the action should deploy.
          dry-run: true    # Don't actually push to pages, just test if we can

      - name: Deploy pages for main-real branch
        if: github.ref == 'refs/heads/main-real'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: slides   # The folder the action should deploy.
